// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/constellation/constellation.proto

package constellation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConstellationService_GetConstellation_FullMethodName = "/constellation.ConstellationService/GetConstellation"
)

// ConstellationServiceClient is the client API for ConstellationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConstellationServiceClient interface {
	GetConstellation(ctx context.Context, in *GetConstellationRequest, opts ...grpc.CallOption) (*GetConstellationResponse, error)
}

type constellationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConstellationServiceClient(cc grpc.ClientConnInterface) ConstellationServiceClient {
	return &constellationServiceClient{cc}
}

func (c *constellationServiceClient) GetConstellation(ctx context.Context, in *GetConstellationRequest, opts ...grpc.CallOption) (*GetConstellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConstellationResponse)
	err := c.cc.Invoke(ctx, ConstellationService_GetConstellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConstellationServiceServer is the server API for ConstellationService service.
// All implementations must embed UnimplementedConstellationServiceServer
// for forward compatibility.
type ConstellationServiceServer interface {
	GetConstellation(context.Context, *GetConstellationRequest) (*GetConstellationResponse, error)
	mustEmbedUnimplementedConstellationServiceServer()
}

// UnimplementedConstellationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConstellationServiceServer struct{}

func (UnimplementedConstellationServiceServer) GetConstellation(context.Context, *GetConstellationRequest) (*GetConstellationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConstellation not implemented")
}
func (UnimplementedConstellationServiceServer) mustEmbedUnimplementedConstellationServiceServer() {}
func (UnimplementedConstellationServiceServer) testEmbeddedByValue()                              {}

// UnsafeConstellationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConstellationServiceServer will
// result in compilation errors.
type UnsafeConstellationServiceServer interface {
	mustEmbedUnimplementedConstellationServiceServer()
}

func RegisterConstellationServiceServer(s grpc.ServiceRegistrar, srv ConstellationServiceServer) {
	// If the following call pancis, it indicates UnimplementedConstellationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConstellationService_ServiceDesc, srv)
}

func _ConstellationService_GetConstellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConstellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstellationServiceServer).GetConstellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConstellationService_GetConstellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstellationServiceServer).GetConstellation(ctx, req.(*GetConstellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConstellationService_ServiceDesc is the grpc.ServiceDesc for ConstellationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConstellationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "constellation.ConstellationService",
	HandlerType: (*ConstellationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConstellation",
			Handler:    _ConstellationService_GetConstellation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/constellation/constellation.proto",
}
